apiVersion: v2
name: sd-servicing-mandate
description: "BIAN Service Domain: Servicing Mandate (Manage pattern, Sales and Service)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Sales and Service"
  bian/business-domain: "Channels"
  bian/asset-type: "Servicing Mandate"
  bian/control-record: "Servicing Mandate Management Plan"
